### ISSUE TITLE
使用sock5代理时报<unexpected protocol version 72>

### ISSUE THREAD

**Issue by Windmill-City** [niuhuan/pica-go#1]
![image](https://user-images.githubusercontent.com/14292823/159106953-a3cd7ce3-edb0-4d95-a292-87778845bca0.png)

**Comment by Windmill-City** [comment]
![image](https://user-images.githubusercontent.com/14292823/159107089-7c584123-ab27-4830-95cf-657f1a64a33b.png)

**Comment by Windmill-City** [comment]
![image](https://user-images.githubusercontent.com/14292823/159107112-39ae0c3c-aeae-425b-9921-71ecfb67997d.png)

**Comment by niuhuan** [comment]
你的Socks5代理版本太高了, Golang1.17不支持。
