### ISSUE TITLE
使用http代理时报<Bad Request>

### ISSUE THREAD

**Issue by Windmill-City** [niuhuan/pica-go#2]
代理参数见 #1

**Comment by Windmill-City** [comment]
![image](https://user-images.githubusercontent.com/14292823/159109570-027d8f1c-18e5-4683-a61c-7ee361a7f9ab.png)

**Comment by Windmill-City** [comment]
![image](https://user-images.githubusercontent.com/14292823/159109576-f7d5ae92-1b24-4ebc-9d61-0a26378e2544.png)

**Comment by niuhuan** [comment]
这里只提供基本的api, 不需要关心代理, 您也许应该将issue提到APP的仓库。
最新的release已经修复了这个问题, 您可以下载试试看。
